@startuml
class ItemActionPanel {
    + AddButon(name:string, onClickAction:Action) : void
    + Toggle(val:bool) : void
    + RemoveOldButtons() : void
    + Update() : void
}
MonoBehaviour <|-- ItemActionPanel
@enduml
