@startuml
class UIInventoryDescription {
    + Awake() : void
    + ResetDescription() : void
    + SetDescription(sprite:Sprite, itemName:string, itemDescription:string) : void
}
MonoBehaviour <|-- UIInventoryDescription
@enduml
