@startuml
class GlobalConstants {
    + {static} <<readonly>> PLAYER_IDLE_ANIMATION_TRIGGER : string = "player_idle_animation_trigger"
    + {static} <<readonly>> PLAYER_WALK_DOWN_ANIMATION_TRIGGER : string = "player_walk_down_animation_trigger"
    + {static} <<readonly>> PLAYER_WALK_UP_ANIMATION_TRIGGER : string = "player_walk_up_animation_trigger"
    + {static} <<readonly>> PLAYER_WALK_SIDE_ANIMATION_TRIGGER : string = "player_walk_side_animation_trigger"
}
ScriptableObject <|-- GlobalConstants
@enduml
